import "./globals.css";
import { Archivo, Roboto } from "next/font/google";

export const roboto = Roboto({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "700", "900"], // regular, medium, bold, black
  style: "normal",
});

export const archivo = Archivo({
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "400", "600", "700"], //  thin-italic, regular, semi-bold, bold,
  style: ["normal", "italic"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${roboto.className} ${archivo.className}`}>
        {children}
      </body>
    </html>
  );
}
