import Footer from './components/shared/Footer/Footer';
import Navbar from './components/shared/Navbar/Navbar';
import './globals.css';
import { Archivo, Roboto } from 'next/font/google';

const roboto = Roboto({
  variable: '--roboto',
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '700', '900'], // regular, medium, bold, black
  style: 'normal',
});

const archivo = Archivo({
  variable: '--archivo',
  subsets: ['latin'],
  display: 'swap',
  weight: ['100', '400', '600', '700'], //  thin-italic, regular, semi-bold, bold,
  style: ['normal', 'italic'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${archivo.variable} ${roboto.variable} pt-[84px]`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
